import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "../public/style/globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <div className="flex min-h-screen flex-col items-center justify-center p-10 sm:p-24 bg-gray-100">
            {children}
          </div>
        </body>
      </Providers>
    </html>
  );
}
